// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/enum_definition.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GUIGUI17F.ProtobufManager {

  /// <summary>Holder for reflection information generated from Protos/enum_definition.proto</summary>
  public static partial class EnumDefinitionReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/enum_definition.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumDefinitionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxQcm90b3MvZW51bV9kZWZpbml0aW9uLnByb3RvEhpndWlndWkxN2YucHJv",
            "dG9idWZfbWFuYWdlciKWAQoORW51bURlZmluaXRpb24SEQoJZW51bV9uYW1l",
            "GAEgASgJEhMKC2FsbG93X2FsaWFzGAIgASgIEhMKC3ZhbHVlX25hbWVzGAMg",
            "AygJEhUKDXZhbHVlX251bWJlcnMYBCADKAUSGAoQcmVzZXJ2ZWRfbnVtYmVy",
            "cxgFIAMoCRIWCg5yZXNlcnZlZF9uYW1lcxgGIAMoCUIeSAOqAhlHVUlHVUkx",
            "N0YuUHJvdG9idWZNYW5hZ2VyYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GUIGUI17F.ProtobufManager.EnumDefinition), global::GUIGUI17F.ProtobufManager.EnumDefinition.Parser, new[]{ "EnumName", "AllowAlias", "ValueNames", "ValueNumbers", "ReservedNumbers", "ReservedNames" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EnumDefinition : pb::IMessage<EnumDefinition>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EnumDefinition> _parser = new pb::MessageParser<EnumDefinition>(() => new EnumDefinition());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EnumDefinition> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GUIGUI17F.ProtobufManager.EnumDefinitionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EnumDefinition() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EnumDefinition(EnumDefinition other) : this() {
      enumName_ = other.enumName_;
      allowAlias_ = other.allowAlias_;
      valueNames_ = other.valueNames_.Clone();
      valueNumbers_ = other.valueNumbers_.Clone();
      reservedNumbers_ = other.reservedNumbers_.Clone();
      reservedNames_ = other.reservedNames_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EnumDefinition Clone() {
      return new EnumDefinition(this);
    }

    /// <summary>Field number for the "enum_name" field.</summary>
    public const int EnumNameFieldNumber = 1;
    private string enumName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EnumName {
      get { return enumName_; }
      set {
        enumName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "allow_alias" field.</summary>
    public const int AllowAliasFieldNumber = 2;
    private bool allowAlias_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool AllowAlias {
      get { return allowAlias_; }
      set {
        allowAlias_ = value;
      }
    }

    /// <summary>Field number for the "value_names" field.</summary>
    public const int ValueNamesFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_valueNames_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> valueNames_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> ValueNames {
      get { return valueNames_; }
    }

    /// <summary>Field number for the "value_numbers" field.</summary>
    public const int ValueNumbersFieldNumber = 4;
    private static readonly pb::FieldCodec<int> _repeated_valueNumbers_codec
        = pb::FieldCodec.ForInt32(34);
    private readonly pbc::RepeatedField<int> valueNumbers_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> ValueNumbers {
      get { return valueNumbers_; }
    }

    /// <summary>Field number for the "reserved_numbers" field.</summary>
    public const int ReservedNumbersFieldNumber = 5;
    private static readonly pb::FieldCodec<string> _repeated_reservedNumbers_codec
        = pb::FieldCodec.ForString(42);
    private readonly pbc::RepeatedField<string> reservedNumbers_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> ReservedNumbers {
      get { return reservedNumbers_; }
    }

    /// <summary>Field number for the "reserved_names" field.</summary>
    public const int ReservedNamesFieldNumber = 6;
    private static readonly pb::FieldCodec<string> _repeated_reservedNames_codec
        = pb::FieldCodec.ForString(50);
    private readonly pbc::RepeatedField<string> reservedNames_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> ReservedNames {
      get { return reservedNames_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EnumDefinition);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EnumDefinition other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EnumName != other.EnumName) return false;
      if (AllowAlias != other.AllowAlias) return false;
      if(!valueNames_.Equals(other.valueNames_)) return false;
      if(!valueNumbers_.Equals(other.valueNumbers_)) return false;
      if(!reservedNumbers_.Equals(other.reservedNumbers_)) return false;
      if(!reservedNames_.Equals(other.reservedNames_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EnumName.Length != 0) hash ^= EnumName.GetHashCode();
      if (AllowAlias != false) hash ^= AllowAlias.GetHashCode();
      hash ^= valueNames_.GetHashCode();
      hash ^= valueNumbers_.GetHashCode();
      hash ^= reservedNumbers_.GetHashCode();
      hash ^= reservedNames_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EnumName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(EnumName);
      }
      if (AllowAlias != false) {
        output.WriteRawTag(16);
        output.WriteBool(AllowAlias);
      }
      valueNames_.WriteTo(output, _repeated_valueNames_codec);
      valueNumbers_.WriteTo(output, _repeated_valueNumbers_codec);
      reservedNumbers_.WriteTo(output, _repeated_reservedNumbers_codec);
      reservedNames_.WriteTo(output, _repeated_reservedNames_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EnumName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(EnumName);
      }
      if (AllowAlias != false) {
        output.WriteRawTag(16);
        output.WriteBool(AllowAlias);
      }
      valueNames_.WriteTo(ref output, _repeated_valueNames_codec);
      valueNumbers_.WriteTo(ref output, _repeated_valueNumbers_codec);
      reservedNumbers_.WriteTo(ref output, _repeated_reservedNumbers_codec);
      reservedNames_.WriteTo(ref output, _repeated_reservedNames_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EnumName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EnumName);
      }
      if (AllowAlias != false) {
        size += 1 + 1;
      }
      size += valueNames_.CalculateSize(_repeated_valueNames_codec);
      size += valueNumbers_.CalculateSize(_repeated_valueNumbers_codec);
      size += reservedNumbers_.CalculateSize(_repeated_reservedNumbers_codec);
      size += reservedNames_.CalculateSize(_repeated_reservedNames_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EnumDefinition other) {
      if (other == null) {
        return;
      }
      if (other.EnumName.Length != 0) {
        EnumName = other.EnumName;
      }
      if (other.AllowAlias != false) {
        AllowAlias = other.AllowAlias;
      }
      valueNames_.Add(other.valueNames_);
      valueNumbers_.Add(other.valueNumbers_);
      reservedNumbers_.Add(other.reservedNumbers_);
      reservedNames_.Add(other.reservedNames_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            EnumName = input.ReadString();
            break;
          }
          case 16: {
            AllowAlias = input.ReadBool();
            break;
          }
          case 26: {
            valueNames_.AddEntriesFrom(input, _repeated_valueNames_codec);
            break;
          }
          case 34:
          case 32: {
            valueNumbers_.AddEntriesFrom(input, _repeated_valueNumbers_codec);
            break;
          }
          case 42: {
            reservedNumbers_.AddEntriesFrom(input, _repeated_reservedNumbers_codec);
            break;
          }
          case 50: {
            reservedNames_.AddEntriesFrom(input, _repeated_reservedNames_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            EnumName = input.ReadString();
            break;
          }
          case 16: {
            AllowAlias = input.ReadBool();
            break;
          }
          case 26: {
            valueNames_.AddEntriesFrom(ref input, _repeated_valueNames_codec);
            break;
          }
          case 34:
          case 32: {
            valueNumbers_.AddEntriesFrom(ref input, _repeated_valueNumbers_codec);
            break;
          }
          case 42: {
            reservedNumbers_.AddEntriesFrom(ref input, _repeated_reservedNumbers_codec);
            break;
          }
          case 50: {
            reservedNames_.AddEntriesFrom(ref input, _repeated_reservedNames_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
