// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/message_definition.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GUIGUI17F.ProtobufManager {

  /// <summary>Holder for reflection information generated from Protos/message_definition.proto</summary>
  public static partial class MessageDefinitionReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/message_definition.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageDefinitionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9Qcm90b3MvbWVzc2FnZV9kZWZpbml0aW9uLnByb3RvEhpndWlndWkxN2Yu",
            "cHJvdG9idWZfbWFuYWdlchocUHJvdG9zL2VudW1fZGVmaW5pdGlvbi5wcm90",
            "bxobUHJvdG9zL21hcF9kZWZpbml0aW9uLnByb3RvGh1Qcm90b3MvZmllbGRf",
            "ZGVmaW5pdGlvbi5wcm90bxodUHJvdG9zL29uZW9mX2RlZmluaXRpb24ucHJv",
            "dG8iswMKEU1lc3NhZ2VEZWZpbml0aW9uEhQKDG1lc3NhZ2VfbmFtZRgBIAEo",
            "CRJEChBlbnVtX2RlZmluaXRpb25zGAIgAygLMiouZ3VpZ3VpMTdmLnByb3Rv",
            "YnVmX21hbmFnZXIuRW51bURlZmluaXRpb24SSgoTbWVzc2FnZV9kZWZpbml0",
            "aW9ucxgDIAMoCzItLmd1aWd1aTE3Zi5wcm90b2J1Zl9tYW5hZ2VyLk1lc3Nh",
            "Z2VEZWZpbml0aW9uEkIKDW5vcm1hbF9maWVsZHMYBCADKAsyKy5ndWlndWkx",
            "N2YucHJvdG9idWZfbWFuYWdlci5GaWVsZERlZmluaXRpb24SPQoKbWFwX2Zp",
            "ZWxkcxgFIAMoCzIpLmd1aWd1aTE3Zi5wcm90b2J1Zl9tYW5hZ2VyLk1hcERl",
            "ZmluaXRpb24SQQoMb25lb2ZfZmllbGRzGAYgAygLMisuZ3VpZ3VpMTdmLnBy",
            "b3RvYnVmX21hbmFnZXIuT25lb2ZEZWZpbml0aW9uEhgKEHJlc2VydmVkX251",
            "bWJlcnMYByADKAkSFgoOcmVzZXJ2ZWRfbmFtZXMYCCADKAlCHkgDqgIZR1VJ",
            "R1VJMTdGLlByb3RvYnVmTWFuYWdlcmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::GUIGUI17F.ProtobufManager.EnumDefinitionReflection.Descriptor, global::GUIGUI17F.ProtobufManager.MapDefinitionReflection.Descriptor, global::GUIGUI17F.ProtobufManager.FieldDefinitionReflection.Descriptor, global::GUIGUI17F.ProtobufManager.OneofDefinitionReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GUIGUI17F.ProtobufManager.MessageDefinition), global::GUIGUI17F.ProtobufManager.MessageDefinition.Parser, new[]{ "MessageName", "EnumDefinitions", "MessageDefinitions", "NormalFields", "MapFields", "OneofFields", "ReservedNumbers", "ReservedNames" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MessageDefinition : pb::IMessage<MessageDefinition>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MessageDefinition> _parser = new pb::MessageParser<MessageDefinition>(() => new MessageDefinition());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MessageDefinition> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GUIGUI17F.ProtobufManager.MessageDefinitionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageDefinition() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageDefinition(MessageDefinition other) : this() {
      messageName_ = other.messageName_;
      enumDefinitions_ = other.enumDefinitions_.Clone();
      messageDefinitions_ = other.messageDefinitions_.Clone();
      normalFields_ = other.normalFields_.Clone();
      mapFields_ = other.mapFields_.Clone();
      oneofFields_ = other.oneofFields_.Clone();
      reservedNumbers_ = other.reservedNumbers_.Clone();
      reservedNames_ = other.reservedNames_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageDefinition Clone() {
      return new MessageDefinition(this);
    }

    /// <summary>Field number for the "message_name" field.</summary>
    public const int MessageNameFieldNumber = 1;
    private string messageName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MessageName {
      get { return messageName_; }
      set {
        messageName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "enum_definitions" field.</summary>
    public const int EnumDefinitionsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::GUIGUI17F.ProtobufManager.EnumDefinition> _repeated_enumDefinitions_codec
        = pb::FieldCodec.ForMessage(18, global::GUIGUI17F.ProtobufManager.EnumDefinition.Parser);
    private readonly pbc::RepeatedField<global::GUIGUI17F.ProtobufManager.EnumDefinition> enumDefinitions_ = new pbc::RepeatedField<global::GUIGUI17F.ProtobufManager.EnumDefinition>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::GUIGUI17F.ProtobufManager.EnumDefinition> EnumDefinitions {
      get { return enumDefinitions_; }
    }

    /// <summary>Field number for the "message_definitions" field.</summary>
    public const int MessageDefinitionsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::GUIGUI17F.ProtobufManager.MessageDefinition> _repeated_messageDefinitions_codec
        = pb::FieldCodec.ForMessage(26, global::GUIGUI17F.ProtobufManager.MessageDefinition.Parser);
    private readonly pbc::RepeatedField<global::GUIGUI17F.ProtobufManager.MessageDefinition> messageDefinitions_ = new pbc::RepeatedField<global::GUIGUI17F.ProtobufManager.MessageDefinition>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::GUIGUI17F.ProtobufManager.MessageDefinition> MessageDefinitions {
      get { return messageDefinitions_; }
    }

    /// <summary>Field number for the "normal_fields" field.</summary>
    public const int NormalFieldsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::GUIGUI17F.ProtobufManager.FieldDefinition> _repeated_normalFields_codec
        = pb::FieldCodec.ForMessage(34, global::GUIGUI17F.ProtobufManager.FieldDefinition.Parser);
    private readonly pbc::RepeatedField<global::GUIGUI17F.ProtobufManager.FieldDefinition> normalFields_ = new pbc::RepeatedField<global::GUIGUI17F.ProtobufManager.FieldDefinition>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::GUIGUI17F.ProtobufManager.FieldDefinition> NormalFields {
      get { return normalFields_; }
    }

    /// <summary>Field number for the "map_fields" field.</summary>
    public const int MapFieldsFieldNumber = 5;
    private static readonly pb::FieldCodec<global::GUIGUI17F.ProtobufManager.MapDefinition> _repeated_mapFields_codec
        = pb::FieldCodec.ForMessage(42, global::GUIGUI17F.ProtobufManager.MapDefinition.Parser);
    private readonly pbc::RepeatedField<global::GUIGUI17F.ProtobufManager.MapDefinition> mapFields_ = new pbc::RepeatedField<global::GUIGUI17F.ProtobufManager.MapDefinition>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::GUIGUI17F.ProtobufManager.MapDefinition> MapFields {
      get { return mapFields_; }
    }

    /// <summary>Field number for the "oneof_fields" field.</summary>
    public const int OneofFieldsFieldNumber = 6;
    private static readonly pb::FieldCodec<global::GUIGUI17F.ProtobufManager.OneofDefinition> _repeated_oneofFields_codec
        = pb::FieldCodec.ForMessage(50, global::GUIGUI17F.ProtobufManager.OneofDefinition.Parser);
    private readonly pbc::RepeatedField<global::GUIGUI17F.ProtobufManager.OneofDefinition> oneofFields_ = new pbc::RepeatedField<global::GUIGUI17F.ProtobufManager.OneofDefinition>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::GUIGUI17F.ProtobufManager.OneofDefinition> OneofFields {
      get { return oneofFields_; }
    }

    /// <summary>Field number for the "reserved_numbers" field.</summary>
    public const int ReservedNumbersFieldNumber = 7;
    private static readonly pb::FieldCodec<string> _repeated_reservedNumbers_codec
        = pb::FieldCodec.ForString(58);
    private readonly pbc::RepeatedField<string> reservedNumbers_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> ReservedNumbers {
      get { return reservedNumbers_; }
    }

    /// <summary>Field number for the "reserved_names" field.</summary>
    public const int ReservedNamesFieldNumber = 8;
    private static readonly pb::FieldCodec<string> _repeated_reservedNames_codec
        = pb::FieldCodec.ForString(66);
    private readonly pbc::RepeatedField<string> reservedNames_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> ReservedNames {
      get { return reservedNames_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MessageDefinition);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MessageDefinition other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MessageName != other.MessageName) return false;
      if(!enumDefinitions_.Equals(other.enumDefinitions_)) return false;
      if(!messageDefinitions_.Equals(other.messageDefinitions_)) return false;
      if(!normalFields_.Equals(other.normalFields_)) return false;
      if(!mapFields_.Equals(other.mapFields_)) return false;
      if(!oneofFields_.Equals(other.oneofFields_)) return false;
      if(!reservedNumbers_.Equals(other.reservedNumbers_)) return false;
      if(!reservedNames_.Equals(other.reservedNames_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MessageName.Length != 0) hash ^= MessageName.GetHashCode();
      hash ^= enumDefinitions_.GetHashCode();
      hash ^= messageDefinitions_.GetHashCode();
      hash ^= normalFields_.GetHashCode();
      hash ^= mapFields_.GetHashCode();
      hash ^= oneofFields_.GetHashCode();
      hash ^= reservedNumbers_.GetHashCode();
      hash ^= reservedNames_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MessageName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MessageName);
      }
      enumDefinitions_.WriteTo(output, _repeated_enumDefinitions_codec);
      messageDefinitions_.WriteTo(output, _repeated_messageDefinitions_codec);
      normalFields_.WriteTo(output, _repeated_normalFields_codec);
      mapFields_.WriteTo(output, _repeated_mapFields_codec);
      oneofFields_.WriteTo(output, _repeated_oneofFields_codec);
      reservedNumbers_.WriteTo(output, _repeated_reservedNumbers_codec);
      reservedNames_.WriteTo(output, _repeated_reservedNames_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MessageName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MessageName);
      }
      enumDefinitions_.WriteTo(ref output, _repeated_enumDefinitions_codec);
      messageDefinitions_.WriteTo(ref output, _repeated_messageDefinitions_codec);
      normalFields_.WriteTo(ref output, _repeated_normalFields_codec);
      mapFields_.WriteTo(ref output, _repeated_mapFields_codec);
      oneofFields_.WriteTo(ref output, _repeated_oneofFields_codec);
      reservedNumbers_.WriteTo(ref output, _repeated_reservedNumbers_codec);
      reservedNames_.WriteTo(ref output, _repeated_reservedNames_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MessageName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MessageName);
      }
      size += enumDefinitions_.CalculateSize(_repeated_enumDefinitions_codec);
      size += messageDefinitions_.CalculateSize(_repeated_messageDefinitions_codec);
      size += normalFields_.CalculateSize(_repeated_normalFields_codec);
      size += mapFields_.CalculateSize(_repeated_mapFields_codec);
      size += oneofFields_.CalculateSize(_repeated_oneofFields_codec);
      size += reservedNumbers_.CalculateSize(_repeated_reservedNumbers_codec);
      size += reservedNames_.CalculateSize(_repeated_reservedNames_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MessageDefinition other) {
      if (other == null) {
        return;
      }
      if (other.MessageName.Length != 0) {
        MessageName = other.MessageName;
      }
      enumDefinitions_.Add(other.enumDefinitions_);
      messageDefinitions_.Add(other.messageDefinitions_);
      normalFields_.Add(other.normalFields_);
      mapFields_.Add(other.mapFields_);
      oneofFields_.Add(other.oneofFields_);
      reservedNumbers_.Add(other.reservedNumbers_);
      reservedNames_.Add(other.reservedNames_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            MessageName = input.ReadString();
            break;
          }
          case 18: {
            enumDefinitions_.AddEntriesFrom(input, _repeated_enumDefinitions_codec);
            break;
          }
          case 26: {
            messageDefinitions_.AddEntriesFrom(input, _repeated_messageDefinitions_codec);
            break;
          }
          case 34: {
            normalFields_.AddEntriesFrom(input, _repeated_normalFields_codec);
            break;
          }
          case 42: {
            mapFields_.AddEntriesFrom(input, _repeated_mapFields_codec);
            break;
          }
          case 50: {
            oneofFields_.AddEntriesFrom(input, _repeated_oneofFields_codec);
            break;
          }
          case 58: {
            reservedNumbers_.AddEntriesFrom(input, _repeated_reservedNumbers_codec);
            break;
          }
          case 66: {
            reservedNames_.AddEntriesFrom(input, _repeated_reservedNames_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            MessageName = input.ReadString();
            break;
          }
          case 18: {
            enumDefinitions_.AddEntriesFrom(ref input, _repeated_enumDefinitions_codec);
            break;
          }
          case 26: {
            messageDefinitions_.AddEntriesFrom(ref input, _repeated_messageDefinitions_codec);
            break;
          }
          case 34: {
            normalFields_.AddEntriesFrom(ref input, _repeated_normalFields_codec);
            break;
          }
          case 42: {
            mapFields_.AddEntriesFrom(ref input, _repeated_mapFields_codec);
            break;
          }
          case 50: {
            oneofFields_.AddEntriesFrom(ref input, _repeated_oneofFields_codec);
            break;
          }
          case 58: {
            reservedNumbers_.AddEntriesFrom(ref input, _repeated_reservedNumbers_codec);
            break;
          }
          case 66: {
            reservedNames_.AddEntriesFrom(ref input, _repeated_reservedNames_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
