// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto_matrix4x4.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GUIGUI17F.ProtobufManager {

  /// <summary>Holder for reflection information generated from proto_matrix4x4.proto</summary>
  public static partial class ProtoMatrix4X4Reflection {

    #region Descriptor
    /// <summary>File descriptor for proto_matrix4x4.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoMatrix4X4Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVwcm90b19tYXRyaXg0eDQucHJvdG8SEHVuaXR5X2V4dGVuc2lvbnMaE3By",
            "b3RvX3ZlY3RvcjQucHJvdG8i1AEKDlByb3RvTWF0cml4NHg0Ei8KB2NvbHVt",
            "bjAYASABKAsyHi51bml0eV9leHRlbnNpb25zLlByb3RvVmVjdG9yNBIvCgdj",
            "b2x1bW4xGAIgASgLMh4udW5pdHlfZXh0ZW5zaW9ucy5Qcm90b1ZlY3RvcjQS",
            "LwoHY29sdW1uMhgDIAEoCzIeLnVuaXR5X2V4dGVuc2lvbnMuUHJvdG9WZWN0",
            "b3I0Ei8KB2NvbHVtbjMYBCABKAsyHi51bml0eV9leHRlbnNpb25zLlByb3Rv",
            "VmVjdG9yNEIeSAOqAhlHVUlHVUkxN0YuUHJvdG9idWZNYW5hZ2VyYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::GUIGUI17F.ProtobufManager.ProtoVector4Reflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GUIGUI17F.ProtobufManager.ProtoMatrix4x4), global::GUIGUI17F.ProtobufManager.ProtoMatrix4x4.Parser, new[]{ "Column0", "Column1", "Column2", "Column3" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ProtoMatrix4x4 : pb::IMessage<ProtoMatrix4x4>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtoMatrix4x4> _parser = new pb::MessageParser<ProtoMatrix4x4>(() => new ProtoMatrix4x4());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtoMatrix4x4> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GUIGUI17F.ProtobufManager.ProtoMatrix4X4Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtoMatrix4x4() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtoMatrix4x4(ProtoMatrix4x4 other) : this() {
      column0_ = other.column0_ != null ? other.column0_.Clone() : null;
      column1_ = other.column1_ != null ? other.column1_.Clone() : null;
      column2_ = other.column2_ != null ? other.column2_.Clone() : null;
      column3_ = other.column3_ != null ? other.column3_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtoMatrix4x4 Clone() {
      return new ProtoMatrix4x4(this);
    }

    /// <summary>Field number for the "column0" field.</summary>
    public const int Column0FieldNumber = 1;
    private global::GUIGUI17F.ProtobufManager.ProtoVector4 column0_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GUIGUI17F.ProtobufManager.ProtoVector4 Column0 {
      get { return column0_; }
      set {
        column0_ = value;
      }
    }

    /// <summary>Field number for the "column1" field.</summary>
    public const int Column1FieldNumber = 2;
    private global::GUIGUI17F.ProtobufManager.ProtoVector4 column1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GUIGUI17F.ProtobufManager.ProtoVector4 Column1 {
      get { return column1_; }
      set {
        column1_ = value;
      }
    }

    /// <summary>Field number for the "column2" field.</summary>
    public const int Column2FieldNumber = 3;
    private global::GUIGUI17F.ProtobufManager.ProtoVector4 column2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GUIGUI17F.ProtobufManager.ProtoVector4 Column2 {
      get { return column2_; }
      set {
        column2_ = value;
      }
    }

    /// <summary>Field number for the "column3" field.</summary>
    public const int Column3FieldNumber = 4;
    private global::GUIGUI17F.ProtobufManager.ProtoVector4 column3_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GUIGUI17F.ProtobufManager.ProtoVector4 Column3 {
      get { return column3_; }
      set {
        column3_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtoMatrix4x4);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtoMatrix4x4 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Column0, other.Column0)) return false;
      if (!object.Equals(Column1, other.Column1)) return false;
      if (!object.Equals(Column2, other.Column2)) return false;
      if (!object.Equals(Column3, other.Column3)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (column0_ != null) hash ^= Column0.GetHashCode();
      if (column1_ != null) hash ^= Column1.GetHashCode();
      if (column2_ != null) hash ^= Column2.GetHashCode();
      if (column3_ != null) hash ^= Column3.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (column0_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Column0);
      }
      if (column1_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Column1);
      }
      if (column2_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Column2);
      }
      if (column3_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Column3);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (column0_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Column0);
      }
      if (column1_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Column1);
      }
      if (column2_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Column2);
      }
      if (column3_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Column3);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (column0_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Column0);
      }
      if (column1_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Column1);
      }
      if (column2_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Column2);
      }
      if (column3_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Column3);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtoMatrix4x4 other) {
      if (other == null) {
        return;
      }
      if (other.column0_ != null) {
        if (column0_ == null) {
          Column0 = new global::GUIGUI17F.ProtobufManager.ProtoVector4();
        }
        Column0.MergeFrom(other.Column0);
      }
      if (other.column1_ != null) {
        if (column1_ == null) {
          Column1 = new global::GUIGUI17F.ProtobufManager.ProtoVector4();
        }
        Column1.MergeFrom(other.Column1);
      }
      if (other.column2_ != null) {
        if (column2_ == null) {
          Column2 = new global::GUIGUI17F.ProtobufManager.ProtoVector4();
        }
        Column2.MergeFrom(other.Column2);
      }
      if (other.column3_ != null) {
        if (column3_ == null) {
          Column3 = new global::GUIGUI17F.ProtobufManager.ProtoVector4();
        }
        Column3.MergeFrom(other.Column3);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (column0_ == null) {
              Column0 = new global::GUIGUI17F.ProtobufManager.ProtoVector4();
            }
            input.ReadMessage(Column0);
            break;
          }
          case 18: {
            if (column1_ == null) {
              Column1 = new global::GUIGUI17F.ProtobufManager.ProtoVector4();
            }
            input.ReadMessage(Column1);
            break;
          }
          case 26: {
            if (column2_ == null) {
              Column2 = new global::GUIGUI17F.ProtobufManager.ProtoVector4();
            }
            input.ReadMessage(Column2);
            break;
          }
          case 34: {
            if (column3_ == null) {
              Column3 = new global::GUIGUI17F.ProtobufManager.ProtoVector4();
            }
            input.ReadMessage(Column3);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (column0_ == null) {
              Column0 = new global::GUIGUI17F.ProtobufManager.ProtoVector4();
            }
            input.ReadMessage(Column0);
            break;
          }
          case 18: {
            if (column1_ == null) {
              Column1 = new global::GUIGUI17F.ProtobufManager.ProtoVector4();
            }
            input.ReadMessage(Column1);
            break;
          }
          case 26: {
            if (column2_ == null) {
              Column2 = new global::GUIGUI17F.ProtobufManager.ProtoVector4();
            }
            input.ReadMessage(Column2);
            break;
          }
          case 34: {
            if (column3_ == null) {
              Column3 = new global::GUIGUI17F.ProtobufManager.ProtoVector4();
            }
            input.ReadMessage(Column3);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
