// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto_player_prefs.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GUIGUI17F.ProtobufManager {

  /// <summary>Holder for reflection information generated from proto_player_prefs.proto</summary>
  public static partial class ProtoPlayerPrefsReflection {

    #region Descriptor
    /// <summary>File descriptor for proto_player_prefs.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoPlayerPrefsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chhwcm90b19wbGF5ZXJfcHJlZnMucHJvdG8SEHVuaXR5X2V4dGVuc2lvbnMi",
            "uAEKEFByb3RvUGxheWVyUHJlZnMSEAoIaW50X2tleXMYASADKAkSEgoKaW50",
            "X3ZhbHVlcxgCIAMoBRISCgpmbG9hdF9rZXlzGAMgAygJEhQKDGZsb2F0X3Zh",
            "bHVlcxgEIAMoAhITCgtzdHJpbmdfa2V5cxgFIAMoCRIVCg1zdHJpbmdfdmFs",
            "dWVzGAYgAygJEhIKCmJ5dGVzX2tleXMYByADKAkSFAoMYnl0ZXNfdmFsdWVz",
            "GAggAygMQh5IA6oCGUdVSUdVSTE3Ri5Qcm90b2J1Zk1hbmFnZXJiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GUIGUI17F.ProtobufManager.ProtoPlayerPrefs), global::GUIGUI17F.ProtobufManager.ProtoPlayerPrefs.Parser, new[]{ "IntKeys", "IntValues", "FloatKeys", "FloatValues", "StringKeys", "StringValues", "BytesKeys", "BytesValues" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ProtoPlayerPrefs : pb::IMessage<ProtoPlayerPrefs>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtoPlayerPrefs> _parser = new pb::MessageParser<ProtoPlayerPrefs>(() => new ProtoPlayerPrefs());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtoPlayerPrefs> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GUIGUI17F.ProtobufManager.ProtoPlayerPrefsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtoPlayerPrefs() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtoPlayerPrefs(ProtoPlayerPrefs other) : this() {
      intKeys_ = other.intKeys_.Clone();
      intValues_ = other.intValues_.Clone();
      floatKeys_ = other.floatKeys_.Clone();
      floatValues_ = other.floatValues_.Clone();
      stringKeys_ = other.stringKeys_.Clone();
      stringValues_ = other.stringValues_.Clone();
      bytesKeys_ = other.bytesKeys_.Clone();
      bytesValues_ = other.bytesValues_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtoPlayerPrefs Clone() {
      return new ProtoPlayerPrefs(this);
    }

    /// <summary>Field number for the "int_keys" field.</summary>
    public const int IntKeysFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_intKeys_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> intKeys_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> IntKeys {
      get { return intKeys_; }
    }

    /// <summary>Field number for the "int_values" field.</summary>
    public const int IntValuesFieldNumber = 2;
    private static readonly pb::FieldCodec<int> _repeated_intValues_codec
        = pb::FieldCodec.ForInt32(18);
    private readonly pbc::RepeatedField<int> intValues_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> IntValues {
      get { return intValues_; }
    }

    /// <summary>Field number for the "float_keys" field.</summary>
    public const int FloatKeysFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_floatKeys_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> floatKeys_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> FloatKeys {
      get { return floatKeys_; }
    }

    /// <summary>Field number for the "float_values" field.</summary>
    public const int FloatValuesFieldNumber = 4;
    private static readonly pb::FieldCodec<float> _repeated_floatValues_codec
        = pb::FieldCodec.ForFloat(34);
    private readonly pbc::RepeatedField<float> floatValues_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> FloatValues {
      get { return floatValues_; }
    }

    /// <summary>Field number for the "string_keys" field.</summary>
    public const int StringKeysFieldNumber = 5;
    private static readonly pb::FieldCodec<string> _repeated_stringKeys_codec
        = pb::FieldCodec.ForString(42);
    private readonly pbc::RepeatedField<string> stringKeys_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> StringKeys {
      get { return stringKeys_; }
    }

    /// <summary>Field number for the "string_values" field.</summary>
    public const int StringValuesFieldNumber = 6;
    private static readonly pb::FieldCodec<string> _repeated_stringValues_codec
        = pb::FieldCodec.ForString(50);
    private readonly pbc::RepeatedField<string> stringValues_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> StringValues {
      get { return stringValues_; }
    }

    /// <summary>Field number for the "bytes_keys" field.</summary>
    public const int BytesKeysFieldNumber = 7;
    private static readonly pb::FieldCodec<string> _repeated_bytesKeys_codec
        = pb::FieldCodec.ForString(58);
    private readonly pbc::RepeatedField<string> bytesKeys_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> BytesKeys {
      get { return bytesKeys_; }
    }

    /// <summary>Field number for the "bytes_values" field.</summary>
    public const int BytesValuesFieldNumber = 8;
    private static readonly pb::FieldCodec<pb::ByteString> _repeated_bytesValues_codec
        = pb::FieldCodec.ForBytes(66);
    private readonly pbc::RepeatedField<pb::ByteString> bytesValues_ = new pbc::RepeatedField<pb::ByteString>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<pb::ByteString> BytesValues {
      get { return bytesValues_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtoPlayerPrefs);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtoPlayerPrefs other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!intKeys_.Equals(other.intKeys_)) return false;
      if(!intValues_.Equals(other.intValues_)) return false;
      if(!floatKeys_.Equals(other.floatKeys_)) return false;
      if(!floatValues_.Equals(other.floatValues_)) return false;
      if(!stringKeys_.Equals(other.stringKeys_)) return false;
      if(!stringValues_.Equals(other.stringValues_)) return false;
      if(!bytesKeys_.Equals(other.bytesKeys_)) return false;
      if(!bytesValues_.Equals(other.bytesValues_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= intKeys_.GetHashCode();
      hash ^= intValues_.GetHashCode();
      hash ^= floatKeys_.GetHashCode();
      hash ^= floatValues_.GetHashCode();
      hash ^= stringKeys_.GetHashCode();
      hash ^= stringValues_.GetHashCode();
      hash ^= bytesKeys_.GetHashCode();
      hash ^= bytesValues_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      intKeys_.WriteTo(output, _repeated_intKeys_codec);
      intValues_.WriteTo(output, _repeated_intValues_codec);
      floatKeys_.WriteTo(output, _repeated_floatKeys_codec);
      floatValues_.WriteTo(output, _repeated_floatValues_codec);
      stringKeys_.WriteTo(output, _repeated_stringKeys_codec);
      stringValues_.WriteTo(output, _repeated_stringValues_codec);
      bytesKeys_.WriteTo(output, _repeated_bytesKeys_codec);
      bytesValues_.WriteTo(output, _repeated_bytesValues_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      intKeys_.WriteTo(ref output, _repeated_intKeys_codec);
      intValues_.WriteTo(ref output, _repeated_intValues_codec);
      floatKeys_.WriteTo(ref output, _repeated_floatKeys_codec);
      floatValues_.WriteTo(ref output, _repeated_floatValues_codec);
      stringKeys_.WriteTo(ref output, _repeated_stringKeys_codec);
      stringValues_.WriteTo(ref output, _repeated_stringValues_codec);
      bytesKeys_.WriteTo(ref output, _repeated_bytesKeys_codec);
      bytesValues_.WriteTo(ref output, _repeated_bytesValues_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += intKeys_.CalculateSize(_repeated_intKeys_codec);
      size += intValues_.CalculateSize(_repeated_intValues_codec);
      size += floatKeys_.CalculateSize(_repeated_floatKeys_codec);
      size += floatValues_.CalculateSize(_repeated_floatValues_codec);
      size += stringKeys_.CalculateSize(_repeated_stringKeys_codec);
      size += stringValues_.CalculateSize(_repeated_stringValues_codec);
      size += bytesKeys_.CalculateSize(_repeated_bytesKeys_codec);
      size += bytesValues_.CalculateSize(_repeated_bytesValues_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtoPlayerPrefs other) {
      if (other == null) {
        return;
      }
      intKeys_.Add(other.intKeys_);
      intValues_.Add(other.intValues_);
      floatKeys_.Add(other.floatKeys_);
      floatValues_.Add(other.floatValues_);
      stringKeys_.Add(other.stringKeys_);
      stringValues_.Add(other.stringValues_);
      bytesKeys_.Add(other.bytesKeys_);
      bytesValues_.Add(other.bytesValues_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            intKeys_.AddEntriesFrom(input, _repeated_intKeys_codec);
            break;
          }
          case 18:
          case 16: {
            intValues_.AddEntriesFrom(input, _repeated_intValues_codec);
            break;
          }
          case 26: {
            floatKeys_.AddEntriesFrom(input, _repeated_floatKeys_codec);
            break;
          }
          case 34:
          case 37: {
            floatValues_.AddEntriesFrom(input, _repeated_floatValues_codec);
            break;
          }
          case 42: {
            stringKeys_.AddEntriesFrom(input, _repeated_stringKeys_codec);
            break;
          }
          case 50: {
            stringValues_.AddEntriesFrom(input, _repeated_stringValues_codec);
            break;
          }
          case 58: {
            bytesKeys_.AddEntriesFrom(input, _repeated_bytesKeys_codec);
            break;
          }
          case 66: {
            bytesValues_.AddEntriesFrom(input, _repeated_bytesValues_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            intKeys_.AddEntriesFrom(ref input, _repeated_intKeys_codec);
            break;
          }
          case 18:
          case 16: {
            intValues_.AddEntriesFrom(ref input, _repeated_intValues_codec);
            break;
          }
          case 26: {
            floatKeys_.AddEntriesFrom(ref input, _repeated_floatKeys_codec);
            break;
          }
          case 34:
          case 37: {
            floatValues_.AddEntriesFrom(ref input, _repeated_floatValues_codec);
            break;
          }
          case 42: {
            stringKeys_.AddEntriesFrom(ref input, _repeated_stringKeys_codec);
            break;
          }
          case 50: {
            stringValues_.AddEntriesFrom(ref input, _repeated_stringValues_codec);
            break;
          }
          case 58: {
            bytesKeys_.AddEntriesFrom(ref input, _repeated_bytesKeys_codec);
            break;
          }
          case 66: {
            bytesValues_.AddEntriesFrom(ref input, _repeated_bytesValues_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
